services:
  booking-service:
    image: bookingservice
    container_name: booking-service
    build:
      context: .
      dockerfile: BookingService/Dockerfile
    environment:
      - ConnectionStrings__PostgreSQL=Host=bookingservice-db;Port=5432;Database=hotelio;Username=hotelio;Password=hotelio
      - Kafka__BootstrapServers=kafka:9092
      - ASPNETCORE_URLS=http://+:9090
    ports:
      - "9090:9090"
    networks:
      - hotelio-net
  bookingservice-db:
    image: postgres:15
    environment:
      POSTGRES_USER: hotelio
      POSTGRES_PASSWORD: hotelio
      POSTGRES_DB: hotelio
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - hotelio-net

volumes:
 db-data:

networks:
  hotelio-net:
    external: true





